# Generated by Django 6.0.5 on 2026-06-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setting',
            table='site_settings',
        ),
    ]
