# Generated by Django 6.0.6 on 2026-06-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('dek', models.TextField(blank=True)),
                ('cat', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(choices=[('Article', 'Article'), ('Report', 'Report'), ('Brief', 'Brief'), ('Analysis', 'Analysis')], default='Article', max_length=20)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('read_time', models.CharField(blank=True, max_length=30)),
                ('cover_url', models.CharField(max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Summit', 'Summit'), ('Salon', 'Salon'), ('Meetup', 'Meetup'), ('Workshop', 'Workshop'), ('Roundtable', 'Roundtable'), ('Other', 'Other')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('orig_price', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('attended', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('flagship', models.BooleanField(default=False)),
                ('past', models.BooleanField(default=False)),
                ('cover_url', models.URLField(blank=True)),
                ('register_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('photo_url', models.URLField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_speakers',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_founder', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('time_tz', models.CharField(blank=True, max_length=50)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('cover_url', models.URLField(blank=True)),
                ('register_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_registrations',
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='unique_event_email_registration')],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team_member_socials',
                'constraints': [models.UniqueConstraint(fields=('team_member', 'platform'), name='unique_team_member_platform')],
            },
        ),
    ]
