# Generated by Django 6.0.6 on 2026-06-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(blank=True, max_length=255)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('time_tz', models.CharField(blank=True, max_length=50)),
                ('cover_url', models.URLField(blank=True)),
                ('registration_link', models.URLField(blank=True)),
                ('status', models.CharField(default='upcoming', max_length=10)),
                ('kind', models.CharField(default='webinar', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webinars',
            },
        ),
    ]
