# Generated by Django 6.0.5 on 2026-05-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='upcoming', max_length=50)),
            ],
        ),
    ]
