# Generated by Django 6.0.5 on 2026-06-07 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0002_webinarlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_upcoming',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='display_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='redirect_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='form_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.TextField(blank=True, default='REGISTRATION OPEN', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinarlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='form_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='register_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='episode_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinarlisting',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinarlisting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webinarlisting',
            name='registration_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinarlisting',
            name='speaker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinarlisting',
            name='status',
            field=models.TextField(blank=True, default='upcoming', null=True),
        ),
        migrations.AlterField(
            model_name='webinarlisting',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='guest',
            table='guests',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='team_members',
        ),
        migrations.AlterModelTable(
            name='webinarlisting',
            table='webinars',
        ),
        migrations.AlterModelTable(
            name='workshop',
            table='workshops',
        ),
        migrations.AlterModelTable(
            name='youtubevideo',
            table='youtube_videos',
        ),
    ]
