# Generated by Django 5.2.15 on 2026-06-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0004_eventregistration_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teammember',
            table='team_members',
        ),
    ]
